# Generated by Django 4.2.2 on 2023-09-28 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='advanced_cost_report_template',
            field=models.FileField(blank=True, default=None, null=True, upload_to='advanced_cost_report_templates/', verbose_name='Шаблон авансового отчета'),
        ),
        migrations.AddField(
            model_name='company',
            name='ceo_name',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='Имя генерального директора'),
        ),
        migrations.AddField(
            model_name='company',
            name='certificate_template',
            field=models.FileField(blank=True, default=None, null=True, upload_to='certificate_templates/', verbose_name='Шаблон командировочного удостоверения'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='bin',
            field=models.BigIntegerField(unique=True, verbose_name='БИН'),
        ),
        migrations.CreateModel(
            name='CompanyLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='legal_documents/', verbose_name='Скан оригинала документа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Скан оригинала документа',
                'verbose_name_plural': 'Сканы оригиналов документов',
            },
        ),
    ]
