# Generated by Django 4.2.2 on 2023-09-28 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='business_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='business_trips.businesstrip', verbose_name='Заявка на командировку'),
        ),
        migrations.AddField(
            model_name='advancedcostreport',
            name='business_trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advanced_cost_reports', to='business_trips.businesstrip', verbose_name='Заявка на командировку'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='assistant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assisted_business_trip', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_business_trip', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_trip', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='departure_city',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='departure_country',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Страна отправления'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='destination_city',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Город назначения'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='destination_country',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Страна назначения'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='duration',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель командировки'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возвращения'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='status',
            field=models.CharField(blank=True, choices=[('awaiting_review', 'Заявка на проверке'), ('fix_required', 'Нужны правки по заявке'), ('soon', 'Скоро командировка'), ('in_trip', 'В командировке'), ('submitting_docs', 'Сдаю документы'), ('awaiting_docs_check', 'На проверке / доки'), ('need_docs_fix', 'Нужны правки / доки'), ('awaiting_advance_report', 'Ожидается авансовый отчет'), ('awaiting_ao_check', 'На проверке / АО'), ('need_ao_fix', 'Нужны правки / АО'), ('all_submitted', 'Все сдано'), ('cancellation', 'Отмена командировки')], default='awaiting_review', max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transportation_type',
            field=models.CharField(choices=[('airplane', 'Самолет'), ('train', 'Поезд'), ('bus', 'Автобус'), ('car', 'Автомобиль'), ('other', 'Другое')], max_length=100, verbose_name='Тип транспорта'),
        ),
        migrations.DeleteModel(
            name='TransportationType',
        ),
    ]
